trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
    mac:
      imageName: 'macos-10.15'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Compile vscode-git-push-progress"
    yarn && yarn install --production=true && yarn compile
    echo ">>> Compiled vscode-git-push-progress"
    echo ">>> Run sample integration test"
    yarn test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'